name: flutter_notes_app
description: A simple Flutter app for taking and securing notes.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter