name: flutter_notes_app
description: A simple Flutter app for taking and securing notes.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  crypto: ^3.0.3
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"